// /components/SummaryCard.tsx

import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";

export function SummaryCard() {
  // --- Placeholder Data ---
  // This text will be generated by your ML model's summary output.
  const summaryData = {
    title: "Model Summary",
    text: "The model analyzed 15,000 data points related to consumer behavior and vehicle performance. Key indicators suggest a 25% increase in demand for electric vehicles with a range over 300 miles. The primary contributing factors include rising fuel costs and improved charging infrastructure. The confidence score for this prediction is 92%.",
  };

  return (
    <Card>
      <CardHeader>
        <CardTitle>{summaryData.title}</CardTitle>
        <CardDescription>High-Level Analysis</CardDescription>
      </CardHeader>
      <CardContent>
        <p className="text-sm text-muted-foreground">{summaryData.text}</p>
      </CardContent>
    </Card>
  );
}